### PR TITLE
added tooltips with descriptions for icon messages

### PR DESCRIPTION
**Pull request by eparker71**

### CODE REVIEW

**Comment by rascalking** [comment]
👍

**Comment by elliottyates** [comment]
Tooltips do not work for me. Are you sure you don't need to initialize them in the js, as per "Opt-in functionality" (http://getbootstrap.com/javascript/#tooltips-examples)?

**Comment by rascalking** [comment]
Huh...yeah, I ran the branch, and I saw "normal" chrome tooltips, not the bootstrap-looking ones.

**Comment by elliottyates** [comment]
Yeah, so the 'title' is what shows up via normal browser tooltip, and the data-original-title is what is shown in the bootstrap-styled tooltips.

**Comment by eparker71** [comment]
yeah, they need to be initialized. I thought they were from the base already, but it was just the chrome ones.

**Pull request merged**
