### PR TITLE
Sorted the course_groups list based on name key

### PR DESCRIPTION
**Pull request by Chris-Thornton-Harvard**
The course groups list is now sorted based on the key 'name'
[TLT-2626](https://jira.huit.harvard.edu/browse/TLT-2626)

### CODE REVIEW

**Comment by Chris-Thornton-Harvard** [comment]
@sapnamysore Made the changes in base.py to point to the course manager secure settings and have it currently hosted on dev for you to test.

**Comment by sapnamysore** [comment]
The changes for sorting and the use of 'coursemanager' oracle user looks good 👍 . 
Lets hold off merging these till we figure out where some of the tables required bulk site create should go

**Comment by cmurtaugh** [comment]
Yeah - looks good - we'll need to coordinate the movement of some of the tables when this is released.

**Comment by sapnamysore** [comment]
@Chris-Thornton-Harvard , Created a subtask outlining the migration..https://jira.huit.harvard.edu/browse/TLT-3118

**Comment by Chris-Thornton-Harvard** [comment]
This PR will handle the DB settings change for canvas_account_admin_tools while @bermudezjd's PR: [Spool queries Oracle to Postgres](https://github.com/Harvard-University-iCommons/tlt-ops/pull/249) handles the table migration to postgres and data population.

**Comment by sapnamysore** [comment]
Looks good! 👍

**Pull request merged**
